[Server]
Port = 2323

[Log]
# 日志文件夹
Director = "logs"
# 输出栈信息的key名
StacktraceKey = "traceStack"
# 是否打印到控制台
LogInConsole = true
# LowercaseLevelEncoder 小写编码器(默认) ,LowercaseColorLevelEncoder 小写带颜色编码器, CapitalLevelEncoder 大写编码器, CapitalColorLevelEncoder 大写带颜色编码器
EncodeLevel = "CapitalColorLevelEncoder"
# txt, json
Format = "txt"

[DB]
DSN = "root:uMIekWqK1P7lTIld@tcp(192.168.13.231:3306)/december?charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"
Debug = true

[Redis]
DB = 0
Addr = "192.168.13.231:6379"
Password = "szpLAavdWPT7w7HB"