[Server]
# http listening address
Host = "0.0.0.0"
# http listening port
Port = 2323
# http graceful shutdown timeout, unit: s
ShutdownTimeout = 30
# max content length: 64M
MaxContentLength = 67108864
# http read timeout, unit: s
ReadTimeout = 20
# http write timeout, unit: s
WriteTimeout = 40
# http idle timeout, unit: s
IdleTimeout = 120
# xss whitelist
XssWhitelist = []

[Log]
# log dir
Director = "logs"
# 输出栈信息的key名
StacktraceKey = "traceStack"
# 是否打印到控制台
LogInConsole = true
# LowercaseLevelEncoder 小写编码器(默认) ,LowercaseColorLevelEncoder 小写带颜色编码器, CapitalLevelEncoder 大写编码器, CapitalColorLevelEncoder 大写带颜色编码器
EncodeLevel = "CapitalColorLevelEncoder"
# txt, json
Format = "txt"

[DB]
DSN = "root:uMIekWqK1P7lTIld@tcp(192.168.13.231:3306)/december?charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"
# enable log
EnableLog = true
# unit: s
MaxLifetime = 7200
# max open connections
MaxOpenConns = 150
# max idle connections
MaxIdleConns = 50
# table prefix
TablePrefix = ""

[Cache]
# redis, memory
CacheType = "redis"

DB = 5
# address, ip:port or ip1:port,ip2:port for cluster and sentinel(SentinelAddrs)
# Addr = "192.168.22.129:6379"
Addr = "192.168.13.231:6379"
#Addr = "127.0.0.1:6379"
#Username = ""
Password = "szpLAavdWPT7w7HB"
#Password = "111111"
# UseTLS = false
# TLSMinVersion = "1.2"
# standalone cluster sentinel
RedisType = "standalone"
# Mastername for sentinel type
# MasterName = "mymaster"
# SentinelUsername = ""
# SentinelPassword = ""
# key expire unit: s
KeyExpire = 7200