package consts

const (
	AMPERSAND  = "&"
	ASTERISK   = "*"
	AT         = "@"
	And        = "and"
	BACKSLASH  = "\\"
	COLON      = ":"
	COMMA      = ","
	CR         = "\r"
	CRLF       = "\r\n"
	DASH       = "-"
	DOLLAR     = "$"
	DOT        = "."
	DOTDOT     = ".."
	DOT_XML    = ".xml"
	EQUALS     = "="
	EMPTY      = ""
	EXCLAM     = "!"
	ISO_8859_1 = "ISO-8859-1"
	GT         = ">"
	GT_EQ      = ">="
	LF         = "\n"
	LPAREN     = "("
	LT         = "<"
	LT_EQ      = "<="
	MINUS      = "-"
	NOT        = "!"
	NOT_EQ     = "!="
	NOT_LIKE   = "not like"
	OR         = "or"
	ONE        = "1"
	PERCENT    = "%"
	PLUS       = "+"
	QUESTION   = "?"
	QUOTE      = "\""
	RPAREN     = ")"
	SEMICOLON  = ";"
	SLASH      = "/"
	SPACE      = " "
	STAR       = "*"
	TILDA      = "~"
	UNDERLINE  = "_"
	UTF8       = "UTF-8"
	US_ASCII   = "US-ASCII"
)
